config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    post 'follow', to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
  end

  authenticated :user do
    root 'places#index', as: :authenticated_root
  end

  root "pages#index"
  get 'place/:id/likes', to: 'places#likes', as: :likes
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :place
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :place
	belongs_to :user
	
	mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :photos



	acts_as_likeable

	geocoded_by :full_place
	after_validation :geocode 

	validates :city, presence: true
	validates :country, presence: true
	validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5  }
	validates :tips, presence: true

	def full_place
		[city, state, country].compact.join(', ')
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]

  has_many :places
  has_many :comments
  has_many :likes
  has_many :photos

  acts_as_followable
  acts_as_follower
  acts_as_liker
  acts_as_mentionable
  acts_as_mentioner
 

  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  }

    def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def new
		@comment. Comment.new
	end

	def create
		@place = Place.find(params[:place_id])
		@place.comments.create(comment_params.merge(user: current_user))
		redirect_to root_path
	end

	private

	def comment_params
		params.require(:comment).permit(:comment)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		render layout: false
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :authenticate_user!

	def create
		@place = Place.find(params[:place_id])
		@place.photos.create(photo_params)	
		redirect_to place_path(@place)
	end

	private

	def photo_params
		params.require(:photo).permit(:caption, :picture, :place_id)
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :likes]
	def index
		@places = Place.paginate(:page => params[:page], :per_page => 3).order('created_at DESC')
		@comment = Comment.new(params[:place_id]) #allows for comment creation in index
	end

	def new
		@place = Place.new
	end

	def likes
		@user = current_user
		@place = Place.find(params[:id])
		@user.like!(@place)
		redirect_to :back
	end

	def unlikes
		@user = current_user
		@place = Place.find(params[:id])
		@user.unlike!(@place)
	end

	def create
		@place = current_user.places.create(place_params)
		if @place.valid?
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show
		@place = Place.find(params[:id])
		@comment = Comment.new
		@photo = Photo.new
	end

	def edit
		@place = Place.find(params[:id])

		if @place.user != current_user
			return render text: 'Not Allowed', status: :forbidden
		end
	end

	def update
		@place = Place.find(params[:id])

		if @place.user != current_user
			return render text: 'Not Allowed', status: :forbidden
		end

		@place.update_attributes(place_params)
		if @place.valid?
			redirect_to place_path(@place)
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@place = Place.find(params[:id])
		if @place.user != current_user
			return render text: 'Not Allowed', status: :forbidden
		end

		@place.destroy
		redirect_to root_path
	end

	private

	def place_params
		params.require(:place).permit(:city, :state, :country, :rating, :tips)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	end

	def show
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelThots</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Asap' rel='stylesheet' type='text/css'>

</head>
<body>
<nav class="navbar navbar-transparent" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TravelThots', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to new_place_path do %>
            <i class = "glyphicon glyphicon-plane"></i>
            Add TravelThot
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'My Profile', '#' %></li> 
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
         	<li><%= link_to 'Sign Up', new_user_registration_path %></li> 
        <% end %>      	
        <li><a href = "#">About TravelThots</li>       
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
  <p class = "alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class = "alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>TravelThots</title>
  		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<%= stylesheet_link_tag 'pages' , media: 'all', 'data-turbolinks-track' => true %>
		<link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Asap' rel='stylesheet' type='text/css'>
	</head>
<body>
	
	<div class = "homecontainer">
		<div class = "hometext">
			<h2>Welcome to</h2>
			<h1>TravelThots</h1>
			<div class = "buttons">
			<%= link_to 'Log In', new_user_session_path, class: 'btn' %>
			<%= link_to 'Sign Up', new_user_registration_path, class: 'btn' %>
		</div>
		</div>

	</div>
	<div class = "infocontainer">
		<h1>How it works:</h1>
		<div class = "col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">
			<ol class = "infolist">
				<li>Sign up</li>
				<li>Add a TravelThot</li>
				<li>Start following friends</li>
				<li>Share TravelThots</li>
			</ol>
		</div>
	</div>
</body>
</html>

app/views/places/edit.html.erb
<div class = "formbox col-xs-12 col-sm-6 col-sm-offset-3">
	<h1>Edit Your Place</h1>
	<%= simple_form_for @place do |f| %>
		<%= f.input :city %>
		<%= f.input :state %>
		<%= f.input :country %>
		<%= f.input :rating %>
		<%= f.input :tips %>
		<br />
		<%= f.submit 'Update', class: 'btn btn-primary' %>
		
	<% end %>
</div>

app/views/places/index.html.erb
<% @places.each do |place| %>
	<% map_id = 'map' + place.id.to_s %>
	<div class = "places col-xs-12 col-sm-6 col-sm-offset-3"> 
		<% if place.user.present? %>
			<small><%= place.user.username %></small>
		<% end %>
		<% if place.state.present? %>
			<h1><%= link_to place.city, place_path(place) %>, <%= place.state %>, <%= place.country %></h1>
		<% else %>
			<h1><%= link_to place.city, place_path(place) %>, <%= place.country %></h1>
		<% end %>
		
	   <% if place.latitude.present? && place.longitude.present? %>
		    
			<div class = "maps">
				<%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{place.latitude},#{place.longitude}&zoom=4&size=300x300&maptype=roadmap&markers=%7Ccolor:0x7278DD%7Clabel:#{place.rating}%7C#{place.latitude},#{place.longitude}&key=#{ENV['GOOGLE_API_KEY']}" %>
			</div>	       
	    <% end %>
	    <div class = "clear"></div>
	    <div class = "icons">
			<%= place.likers(User).count %> likes
			<% if current_user && current_user.likes?(place) %>
				<%= image_tag('blueheart.png', id: 'heart') %>
				<%= link_to image_tag('comment.png'), "#" + place.id.to_s + "Modal", :data => { :toggle => "modal"} %>
			<% else %>
				<%= link_to image_tag('heart.png', id: 'heart'), likes_path(place) %>
				<%= link_to image_tag('comment.png'), "#" + place.id.to_s + "Modal", :data => { :toggle => "modal"} %>
			<% end %>
			
		</div>

		<script>
		$("#heart").click(function(){
			$("#heart").attr("src", "<%= image_path 'blueheart.png' %>");
		})
			
		</script>
		<div class = "comments">
		<h3>Comments</h3>
		<% place.comments.each do |comment| %>
			<div class = "commentsline">
				<h4 style = "display: inline"><%= comment.user.username %>:</h4>
				<small style + 'display: inline' class = "pull-right"><%= comment.created_at.strftime("%b%d'%y") %></small>
				<p style = 'display: inline'><%= comment.comment %></p>
					
			</div>
		<% end %>
	</div>

	</div>

<!-- Modal -->
<div class="modal fade" id= "<%= place.id %>Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Comment</h4>
      </div>
      
        <%= simple_form_for @comment, url: place_comments_path(place) do |f| %>
	  		<div class = "modal-body">
		  		<%= f.input :comment %>
		  	</div>	
           <div class="modal-footer">
        		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        		<%= f.submit "Add a Comment", class: 'btn btn-primary' %>
      		</div>
      		<% end %>
      </div>
    </div>
  </div>
</div>

<% end %>



<div class = "clear"></div>
<%= will_paginate @places %>

app/views/places/new.html.erb
<div class = "formbox col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
	<h1>Enter a new place!</h1>
	<%= simple_form_for @place do |f| %>
		<%= f.input :city %>
		<%= f.input :state %>
		<%= f.input :country %>
		<%= f.input :rating %>
		<%= f.input :tips %>
		<br />
		<%= f.submit 'Post', class: 'btn btn-primary' %>
		
	<% end %>
</div>

app/views/places/show.html.erb
<div class = "col-xs-12 col-sm-10 col-sm-offset-1">
	<div class = "placebox col-xs-12 col-sm-8">
		<h1><%= @place.city %></h1>
		<% if @place.state.present? %>
			<h2><%= @place.state %>, <%= @place.country %></h2>
		<% else %>
			<h2><%= @place.country %></h2>
		<% end %>
		
		<% if @place.latitude.present? && @place.longitude.present? %>
	  
		    <script>

				function initMap() {
				  var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

				  var map = new google.maps.Map(document.getElementById('map'), {
				    zoom: 4,
				    center: myLatLng
				  });

				  var marker = new google.maps.Marker({
				    position: myLatLng,
				    map: map,
				    title: 'Hello World!'
				  });
				}

		    </script>
		    <script async defer
		        src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap"></script>
	        <div id = "map" class = "maps"></div>
	     <% end %>
	        <div class = "icons">
	        	<%= @place.user.username %>'s Rating:
		        <% if @place.rating == 1 %>
		        	<%= image_tag('airplane.png') %>
		        <% elsif @place.rating == 2 %>
		        	<%= image_tag('airplane.png') %>
		        	<%= image_tag('airplane.png') %>
		        <% elsif @place.rating == 3 %>
		        	<%= image_tag('airplane.png') %>
		        	<%= image_tag('airplane.png') %>
		        	<%= image_tag('airplane.png') %>
		        <% elsif @place.rating == 4 %>
		        	<%= image_tag('airplane.png') %>
		        	<%= image_tag('airplane.png') %>
		        	<%= image_tag('airplane.png') %>
		        	<%= image_tag('airplane.png') %>
		        <% else %>
		        	<%= image_tag('airplane.png') %>
		        	<%= image_tag('airplane.png') %>
		        	<%= image_tag('airplane.png') %>
		        	<%= image_tag('airplane.png') %>
		        	<%= image_tag('airplane.png') %>
		        <% end %>
		    </div>
		
		<h3><%= @place.user.username %>'s TravelThots: </h3>
		<h4><%= @place.tips %></h4>
		<br />
		
		<% if current_user && current_user == @place.user %>
			<%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
			<%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: "Are you sure you want to delete this?"}, class: 'btn btn-danger' %>
			<%= link_to 'Add Photo', "#addPhotoModal", :data => { :toggle => "modal"}, class: 'btn btn-primary' %>
		<% end %>
		<br />
		<div class = "icons">
			<%= @place.likers(User).count %> likes
			<% if current_user && current_user.likes?(@place) %>
				<%= image_tag('blueheart.png', id: 'heart') %>
				<%= link_to image_tag('comment.png'), "#myModal", :data => { :toggle => "modal"} %>
			<% else %>
				<%= link_to image_tag('heart.png', id: 'heart'), likes_path(@place) %>
				<%= link_to image_tag('comment.png'), "#myModal", :data => { :toggle => "modal"} %>
			<% end %>
			
		</div>
		
		
		<script>
		$("#heart").click(function(){
			$("#heart").attr("src", "<%= image_path 'blueheart.png' %>");
		})
			
		</script>

	</div>
	<div class = "comments col-xs-12 col-sm-4">
		<h3>Comments</h3>
		<% @place.comments.each do |comment| %>
			<div class = "commentsline">
				<h4 style = "display: inline"><%= comment.user.username %>:</h4>
				<small style = 'display: inline' class = "pull-right"><%= comment.created_at.strftime("%b%d'%y") %></small>
				<p style = 'display: inline'><%= comment.comment %></p>
					
			</div>
		<% end %>
		<h3><%= @place.user.username %>'s Photos of <%= @place.city %></h3>
		<% @place.photos.each do |photo| %>
			<div class = "placephotos col-xs-12 col-sm-6">
				<%= image_tag photo.picture, class: "popPic"  %>
				<small><%= photo.caption %></small>
					
			</div>
		<% end %>
	</div>
</div>


<script>
	$(function() {
		$('.popPic').on('click', function() {
			$('.imagepreview').attr('src', $(this).attr('src'));
			$('#imagemodal').modal('show');   
		});		
});
</script>

<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">              
      <div class="modal-body">
      	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <img src="" class="imagepreview" style="width: 100%;" >
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Comment</h4>
      </div>
      
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
	  		<div class = "modal-body">
		  		<%= f.input :comment %>
		  	</div>	
           <div class="modal-footer">
        		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        		<%= f.submit "Add a Comment", class: 'btn btn-primary' %>
      		</div>
      		<% end %>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="addPhotoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Photo</h4>
      </div>
      
        <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
	  		<div class = "modal-body">
	  			<%= f.input :picture %>
		  		<%= f.input :caption %>
		  	</div>	
           <div class="modal-footer">
        		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        		<%= f.submit "Add a Photo", class: 'btn btn-primary' %>
      		</div>
      		<% end %>
      </div>
    </div>
  </div>
</div>